# Read the Docs config for CausalBGM-only website
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

sphinx:
  configuration: docs/source/conf_causalbgm.py

python:
  install:
    - requirements: docs/requirements.txt
